#!/usr/bin/env python3
"""
Seeded LD-ENSF-style assimilation test for hydro_surrogate_light.

Pipeline:
1. Load the raw trajectory and the observation key points generated by
   `create_ldensf_dataset.py`.
2. Encode the noisy observations with the trained LSTM.
3. Propagate the LDNet latent dynamics forward and apply an LD-ENSF-style
   ensemble score update in latent space at every time step.
4. Render a domain GIF with truth, forecast, and assimilation panels.
"""

from __future__ import annotations

import argparse
import math
import re
import random
import sys
from pathlib import Path

import matplotlib
import numpy as np
import torch

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib import animation as mpl_animation
from tqdm import tqdm


REPO_ROOT = Path(__file__).resolve().parent
sys.path.append(str(REPO_ROOT))

from efficient_fourier_ldnet import EfficientFourierLDNN
from src.encoder import TimeSeriesLSTM


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def resolve_device(device_str: str) -> torch.device:
    if device_str == "auto":
        return torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    if "cuda" in device_str and not torch.cuda.is_available():
        return torch.device("cpu")
    return torch.device(device_str)


def _resolve_path(base_path: Path, path: Path) -> Path:
    return path if path.is_absolute() else base_path / path


def _infer_use_static_features(model_path: Path, user_choice: bool | None) -> bool:
    if user_choice is not None:
        return user_choice
    return model_path.name.lower() == "cldnet" or "static" in model_path.name.lower()


def _load_reduced_trajectory(
    data_root: Path,
    traj_id: int,
    use_static_features: bool,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    flow = np.load(data_root / f"flow_variables_traj{traj_id}.npy", mmap_mode="r")
    coords = np.load(data_root / f"coords_traj{traj_id}.npy", mmap_mode="r")
    rain = np.load(data_root / f"rain_source_traj{traj_id}.npy", mmap_mode="r")
    if use_static_features:
        static_path = data_root / f"static_features_traj{traj_id}.npy"
        if not static_path.exists():
            raise FileNotFoundError(f"Missing static features for traj {traj_id}: {static_path}")
        static = np.load(static_path, mmap_mode="r")
        coords = np.concatenate([coords, static], axis=-1)
    return flow, coords, rain


def _list_trajectory_ids(data_root: Path) -> list[int]:
    traj_ids: list[int] = []
    for path in data_root.glob("rain_source_traj*.npy"):
        match = re.search(r"traj(\d+)\.npy$", path.name)
        if match is not None:
            traj_ids.append(int(match.group(1)))
    traj_ids = sorted(set(traj_ids))
    if not traj_ids:
        raise FileNotFoundError(f"No rain_source_traj*.npy files found in {data_root}")
    return traj_ids


def _select_background_traj_id(
    traj_ids: list[int],
    target_traj_id: int,
    requested_traj_id: int | None,
) -> int:
    if requested_traj_id is not None:
        if requested_traj_id not in traj_ids:
            raise ValueError(f"Requested background traj id {requested_traj_id} is not available")
        return requested_traj_id

    ordered = sorted(traj_ids)
    for traj_id in ordered:
        if traj_id > target_traj_id:
            return traj_id
    for traj_id in ordered:
        if traj_id != target_traj_id:
            return traj_id
    raise ValueError("Need at least two distinct trajectories to choose a background rain source")


def _build_coords(h_dim: int, w_dim: int) -> np.ndarray:
    x = 2.0 * (np.arange(w_dim, dtype=np.float32) / w_dim - 0.5)
    aspect = h_dim / float(w_dim)
    y = 2.0 * (np.arange(h_dim, dtype=np.float32) / h_dim - 0.5) * aspect
    x_coords = np.tile(x, h_dim)
    y_coords = np.repeat(y, w_dim)
    return np.stack([x_coords, y_coords], axis=1)[None, :, :].astype(np.float32)


def _resolve_scatter_indices(valid_mask: np.ndarray, h_dim: int, w_dim: int, coords: np.ndarray) -> np.ndarray:
    mask_indices = np.flatnonzero(valid_mask.reshape(-1).astype(bool))
    n_reduced = int(coords.shape[1])
    if mask_indices.size < n_reduced:
        raise ValueError(f"Mask points {mask_indices.size} < reduced points {n_reduced}")
    if mask_indices.size == n_reduced:
        return mask_indices

    full_coords = _build_coords(h_dim, w_dim).reshape(-1, 2).astype(np.float16)
    masked_coords = full_coords[mask_indices]
    reduced_xy = coords[0, :, :2].astype(np.float16, copy=False)

    coord_to_flat: dict[tuple[float, float], int] = {}
    for idx, xy in zip(mask_indices, masked_coords):
        coord_to_flat[(float(xy[0]), float(xy[1]))] = int(idx)

    scatter_indices = np.empty(n_reduced, dtype=np.int64)
    for j, xy in enumerate(reduced_xy):
        key = (float(xy[0]), float(xy[1]))
        flat_idx = coord_to_flat.get(key)
        if flat_idx is None:
            raise ValueError(f"Could not map reduced coord {key} at index {j}")
        scatter_indices[j] = flat_idx
    return scatter_indices


def _flatten_obs(obs: np.ndarray) -> np.ndarray:
    if obs.ndim != 4:
        raise ValueError(f"Expected observations with shape (N, T, K, C); got {obs.shape}")
    return obs.reshape(obs.shape[0], obs.shape[1], -1)


def _normalize(x: torch.Tensor, mean: torch.Tensor | None, std: torch.Tensor | None) -> torch.Tensor:
    if mean is None or std is None:
        return x
    view_shape = (1,) * (x.ndim - 1) + (mean.shape[0],)
    return (x - mean.reshape(view_shape)) / std.reshape(view_shape)


def _denormalize(x: torch.Tensor, mean: torch.Tensor | None, std: torch.Tensor | None) -> torch.Tensor:
    if mean is None or std is None:
        return x
    view_shape = (1,) * (x.ndim - 1) + (mean.shape[0],)
    return x * std.reshape(view_shape) + mean.reshape(view_shape)


def _relative_l2_error(truth: np.ndarray, pred: np.ndarray) -> np.ndarray:
    truth_flat = truth.reshape(truth.shape[0], -1)
    pred_flat = pred.reshape(pred.shape[0], -1)
    valid = np.isfinite(truth_flat) & np.isfinite(pred_flat)
    denom = np.linalg.norm(np.where(valid, truth_flat, 0.0), axis=1) + 1e-12
    return np.linalg.norm(np.where(valid, pred_flat - truth_flat, 0.0), axis=1) / denom


def _relative_l2_scalar(truth: np.ndarray, pred: np.ndarray) -> float:
    truth_flat = np.asarray(truth, dtype=np.float32).reshape(-1)
    pred_flat = np.asarray(pred, dtype=np.float32).reshape(-1)
    valid = np.isfinite(truth_flat) & np.isfinite(pred_flat)
    if not np.any(valid):
        return float("nan")
    truth_valid = truth_flat[valid]
    pred_valid = pred_flat[valid]
    return float(np.linalg.norm(pred_valid - truth_valid) / (np.linalg.norm(truth_valid) + 1e-12))


def _r2_scalar(truth: np.ndarray, pred: np.ndarray) -> float:
    truth_flat = np.asarray(truth, dtype=np.float32).reshape(-1)
    pred_flat = np.asarray(pred, dtype=np.float32).reshape(-1)
    valid = np.isfinite(truth_flat) & np.isfinite(pred_flat)
    if not np.any(valid):
        return float("nan")

    truth_valid = truth_flat[valid]
    pred_valid = pred_flat[valid]
    ss_res = float(np.sum((pred_valid - truth_valid) ** 2))
    ss_tot = float(np.sum((truth_valid - truth_valid.mean()) ** 2))
    if ss_tot <= 0.0:
        return float("nan")
    return float(1.0 - ss_res / ss_tot)


def _trajectory_metrics(truth: np.ndarray, pred: np.ndarray) -> tuple[float, float, float]:
    truth_flat = np.asarray(truth, dtype=np.float32).reshape(-1)
    pred_flat = np.asarray(pred, dtype=np.float32).reshape(-1)
    valid = np.isfinite(truth_flat) & np.isfinite(pred_flat)
    if not np.any(valid):
        return float("nan"), float("nan"), float("nan")

    truth_valid = truth_flat[valid]
    pred_valid = pred_flat[valid]
    error = pred_valid - truth_valid
    rmse = float(np.sqrt(np.mean(error**2)))
    truth_rms = float(np.sqrt(np.mean(truth_valid**2)))
    rel_rmse = float(rmse / (truth_rms + 1e-12))
    ss_res = float(np.sum(error**2))
    ss_tot = float(np.sum((truth_valid - truth_valid.mean()) ** 2))
    r2 = float(1.0 - ss_res / ss_tot) if ss_tot > 0.0 else float("nan")
    return rel_rmse, rmse, r2


def _load_ldnet_model(
    *,
    opt: argparse.Namespace,
    device: torch.device,
    dim_u: int,
    dim_x: int,
    dim_y: int,
) -> EfficientFourierLDNN:
    model = EfficientFourierLDNN(
        opt.fourier_mapping_size,
        [opt.num_latent_states + dim_u] + opt.NN_dyn_depth * [opt.NN_dyn_width] + [opt.num_latent_states],
        [opt.num_latent_states + dim_x] + opt.NN_rec_depth * [opt.NN_rec_width] + [dim_y],
        activation=opt.activation,
        kernel_initializer=opt.kernel_initializer,
        chunk_size=opt.chunk_size,
    )

    model_dir = opt.base_path / opt.model_path
    if opt.dyn_checkpoint is not None and opt.rec_checkpoint is not None:
        dyn_ckpt = _resolve_path(opt.base_path, opt.dyn_checkpoint)
        rec_ckpt = _resolve_path(opt.base_path, opt.rec_checkpoint)
        b_ckpt = _resolve_path(opt.base_path, opt.B_checkpoint) if opt.B_checkpoint is not None else None
    else:
        dyn_ckpt = model_dir / f"dyn_{opt.checkpoint_epoch}.ckpt"
        rec_ckpt = model_dir / f"rec_{opt.checkpoint_epoch}.ckpt"
        b_ckpt = model_dir / f"B_{opt.checkpoint_epoch}.ckpt"

    model.dyn.load_state_dict(torch.load(dyn_ckpt, map_location="cpu", weights_only=False))
    model.rec.load_state_dict(torch.load(rec_ckpt, map_location="cpu", weights_only=False))
    if b_ckpt is not None and b_ckpt.exists():
        model.B.load_state_dict(torch.load(b_ckpt, map_location="cpu", weights_only=False))

    model.to(device)
    model.eval()
    return model


def _load_encoder(checkpoint_path: Path, device: torch.device) -> tuple[TimeSeriesLSTM, dict[str, torch.Tensor | None], bool]:
    ckpt = torch.load(checkpoint_path, map_location="cpu", weights_only=False)
    config = ckpt["model_config"]
    model = TimeSeriesLSTM(
        input_size=int(config["input_size"]),
        hidden_size=int(config["hidden_size"]),
        output_size=int(config["output_size"]),
        num_layers=int(config["num_layers"]),
        dropout=float(config["dropout"]),
    )
    model.load_state_dict(ckpt["model_state_dict"])
    model.to(device)
    model.eval()

    stats = ckpt.get("stats", {})
    obs_mean = stats.get("obs_mean")
    obs_std = stats.get("obs_std")
    latent_mean = stats.get("latent_mean")
    latent_std = stats.get("latent_std")

    def _maybe_tensor(value):
        if value is None:
            return None
        if isinstance(value, torch.Tensor):
            return value.float()
        return torch.as_tensor(value, dtype=torch.float32)

    return model, {
        "obs_mean": _maybe_tensor(obs_mean),
        "obs_std": _maybe_tensor(obs_std),
        "latent_mean": _maybe_tensor(latent_mean),
        "latent_std": _maybe_tensor(latent_std),
    }, bool(ckpt.get("normalize", False))


def _ensemble_score_posterior(
    prior: torch.Tensor,
    obs_latent: torch.Tensor,
    *,
    time_steps: int,
    obs_sigma: float,
    latent_scaling: float,
    eps_alpha: float,
    generator: torch.Generator,
) -> torch.Tensor:
    device = prior.device
    dtype = prior.dtype
    prior_scaled = prior * latent_scaling
    obs_scaled = obs_latent * latent_scaling

    ensemble_size, latent_dim = prior_scaled.shape
    xt = torch.randn((ensemble_size, latent_dim), device=device, dtype=dtype, generator=generator)

    def cond_alpha(t: float) -> float:
        return 1.0 - (1.0 - eps_alpha) * t

    def cond_sigma_sq(t: float) -> float:
        return max(t, 1e-6)

    def f_func(t: float) -> float:
        alpha_t = cond_alpha(t)
        return -(1.0 - eps_alpha) / alpha_t

    def g_sq(t: float) -> float:
        sigma2_t = cond_sigma_sq(t)
        return max(1e-12, 1.0 - 2.0 * f_func(t) * sigma2_t)

    dt = 1.0 / float(time_steps)
    t = 1.0
    for _ in range(time_steps):
        alpha_t = cond_alpha(t)
        sigma2_t = cond_sigma_sq(t)
        f_t = f_func(t)
        diffuse_sq = g_sq(t)
        diffuse = math.sqrt(diffuse_sq)
        tau = 1.0 - t
        score_likelihood = tau * (-(xt - obs_scaled.unsqueeze(0)) / (obs_sigma**2 + 1e-12))
        drift = f_t * xt + diffuse_sq * ((xt - alpha_t * prior_scaled) / sigma2_t) - diffuse_sq * score_likelihood
        xt = xt - dt * drift + math.sqrt(dt) * diffuse * torch.randn(
            xt.shape, device=device, dtype=dtype, generator=generator
        )
        t = max(0.0, t - dt)

    return xt / latent_scaling


def _series_to_grid(series: np.ndarray, coarse_shape: tuple[int, int], coarse_valid_flat: np.ndarray) -> np.ndarray:
    grid = np.full((series.shape[0], *coarse_shape), np.nan, dtype=np.float32)
    grid.reshape(series.shape[0], -1)[:, coarse_valid_flat] = series.astype(np.float32, copy=False)
    return grid


def _make_map_gif(
    *,
    time: np.ndarray,
    truth_grid: np.ndarray,
    obs_coords: np.ndarray,
    obs_values: np.ndarray,
    obs_err_values: np.ndarray,
    forecast_grid: np.ndarray,
    assim_grid: np.ndarray,
    left_vmin: float,
    left_vmax: float,
    err_vmax: float,
    extent: tuple[float, float, float, float],
    out_path: Path,
    fps: int,
    stride: int,
) -> None:
    time = np.asarray(time)
    stride = max(1, int(stride))
    frame_indices = list(range(0, len(time), stride))
    if frame_indices[-1] != len(time) - 1:
        frame_indices.append(len(time) - 1)

    fig, axes = plt.subplots(2, 3, figsize=(15.0, 11.5), sharex=False, sharey=False)
    left_cmap = plt.get_cmap("Blues").copy()
    left_cmap.set_bad(color=(1.0, 1.0, 1.0, 0.0))
    err_cmap = plt.get_cmap("magma").copy()
    err_cmap.set_bad(color=(1.0, 1.0, 1.0, 0.0))

    top_titles = [
        "Truth + noisy observations",
        "Forecast from background rainfall",
        "LD-ENSF assimilation",
    ]
    bottom_titles = [
        "Observation error",
        "Forecast error",
        "Assimilation error",
    ]

    top_images: list[object] = []
    bottom_images: list[object] = []
    obs_scatter = None
    obs_err_scatter = None

    for col in range(3):
        ax_top = axes[0, col]
        ax_bottom = axes[1, col]
        ax_top.set_title(top_titles[col], fontsize=11)
        ax_bottom.set_title(bottom_titles[col], fontsize=11)
        ax_top.set_xlim(extent[0], extent[1])
        ax_top.set_ylim(extent[2], extent[3])
        ax_bottom.set_xlim(extent[0], extent[1])
        ax_bottom.set_ylim(extent[2], extent[3])
        ax_top.set_aspect("equal")
        ax_bottom.set_aspect("equal")
        ax_top.set_xticks([])
        ax_top.set_yticks([])
        ax_bottom.set_xticks([])
        ax_bottom.set_yticks([])

        if col == 0:
            top_im = ax_top.imshow(
                truth_grid[0],
                origin="lower",
                extent=extent,
                cmap=left_cmap,
                vmin=left_vmin,
                vmax=left_vmax,
                interpolation="nearest",
                aspect="equal",
            )
            obs_scatter = ax_top.scatter(
                obs_coords[:, 0],
                obs_coords[:, 1],
                c=obs_values[0],
                cmap=left_cmap,
                vmin=left_vmin,
                vmax=left_vmax,
                s=8,
                edgecolors="black",
                linewidths=0.15,
                alpha=0.95,
            )
            obs_err_scatter = ax_bottom.scatter(
                obs_coords[:, 0],
                obs_coords[:, 1],
                c=obs_err_values[0],
                cmap=err_cmap,
                vmin=0.0,
                vmax=err_vmax,
                s=8,
                edgecolors="black",
                linewidths=0.15,
                alpha=0.95,
            )
            bottom_im = obs_err_scatter
        elif col == 1:
            top_im = ax_top.imshow(
                forecast_grid[0],
                origin="lower",
                extent=extent,
                cmap=left_cmap,
                vmin=left_vmin,
                vmax=left_vmax,
                interpolation="nearest",
                aspect="equal",
            )
            bottom_im = ax_bottom.imshow(
                np.abs(forecast_grid[0] - truth_grid[0]),
                origin="lower",
                extent=extent,
                cmap=err_cmap,
                vmin=0.0,
                vmax=err_vmax,
                interpolation="nearest",
                aspect="equal",
            )
        else:
            top_im = ax_top.imshow(
                assim_grid[0],
                origin="lower",
                extent=extent,
                cmap=left_cmap,
                vmin=left_vmin,
                vmax=left_vmax,
                interpolation="nearest",
                aspect="equal",
            )
            bottom_im = ax_bottom.imshow(
                np.abs(assim_grid[0] - truth_grid[0]),
                origin="lower",
                extent=extent,
                cmap=err_cmap,
                vmin=0.0,
                vmax=err_vmax,
                interpolation="nearest",
                aspect="equal",
            )

        top_images.append(top_im)
        bottom_images.append(bottom_im)

    for col in range(3):
        axes[1, col].set_xlabel("x")
    for row in range(2):
        axes[row, 0].set_ylabel("y")

    suptitle = fig.suptitle("Hydro LD-ENSF comparison", fontsize=13, y=0.98)
    fig.subplots_adjust(left=0.035, right=0.995, bottom=0.06, top=0.93, wspace=0.08, hspace=0.12)

    def update(frame_idx: int):
        idx = frame_indices[frame_idx]
        suptitle.set_text(f"Hydro LD-ENSF comparison | frame {frame_idx + 1}/{len(frame_indices)} | time step {idx}")
        top_images[0].set_data(truth_grid[idx])
        if obs_scatter is not None:
            obs_scatter.set_array(obs_values[idx])
        if obs_err_scatter is not None:
            obs_err_scatter.set_array(obs_err_values[idx])

        top_images[1].set_data(forecast_grid[idx])
        bottom_images[1].set_data(np.abs(forecast_grid[idx] - truth_grid[idx]))

        top_images[2].set_data(assim_grid[idx])
        bottom_images[2].set_data(np.abs(assim_grid[idx] - truth_grid[idx]))
        artists = top_images + bottom_images
        if obs_scatter is not None:
            artists.append(obs_scatter)
        if obs_err_scatter is not None:
            artists.append(obs_err_scatter)
        return artists

    anim = mpl_animation.FuncAnimation(
        fig,
        update,
        frames=len(frame_indices),
        interval=1000.0 / max(1, fps),
        blit=False,
        repeat=True,
    )

    if mpl_animation.writers.is_available("pillow"):
        writer = mpl_animation.PillowWriter(fps=max(1, fps))
    elif mpl_animation.writers.is_available("imagemagick"):
        writer = mpl_animation.ImageMagickWriter(fps=max(1, fps))
    else:
        raise RuntimeError("No GIF writer available. Install pillow or ImageMagick.")

    anim.save(str(out_path), writer=writer, dpi=120)
    plt.close(fig)


def create_options() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base-path", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--data-root", type=Path, default=Path("data/postprocessed/illinois"))
    parser.add_argument("--dataset-path", type=Path, default=Path("data/postprocessed/illinois/observation_ldensf_dataset.pth"))
    parser.add_argument("--model-path", type=Path, default=Path("checkpoints/cldnet"))
    parser.add_argument("--encoder-checkpoint", type=Path, default=Path("checkpoints/ldensf_lstm/lstm_ldensf.ckpt"))
    parser.add_argument("--output-dir", type=Path, default=Path("ldensf_results"))
    parser.add_argument("--traj-id", type=int, default=0)
    parser.add_argument("--background-traj-id", type=int, default=None)
    parser.add_argument("--device", type=str, default="auto")
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--da-seed", type=int, default=None)
    parser.add_argument("--checkpoint-epoch", type=int, default=539)
    parser.add_argument("--dyn-checkpoint", type=Path, default=None)
    parser.add_argument("--rec-checkpoint", type=Path, default=None)
    parser.add_argument("--B-checkpoint", type=Path, default=None)
    parser.add_argument("--num-latent-states", type=int, default=200)
    parser.add_argument("--fourier-mapping-size", type=int, default=32)
    parser.add_argument("--NN-dyn-depth", type=int, default=8)
    parser.add_argument("--NN-dyn-width", type=int, default=50)
    parser.add_argument("--NN-rec-depth", type=int, default=10)
    parser.add_argument("--NN-rec-width", type=int, default=300)
    parser.add_argument("--activation", type=str, default="relu")
    parser.add_argument("--kernel-initializer", type=str, default="Glorot normal")
    parser.add_argument("--chunk-size", type=int, default=10000)
    parser.add_argument("--ensemble-size", type=int, default=20)
    parser.add_argument("--obs-noise-std", type=float, default=0.05)
    parser.add_argument("--obs-sigma", type=float, default=0.1)
    parser.add_argument("--latent-scaling", type=float, default=1.0)
    parser.add_argument("--eps-alpha", type=float, default=0.05)
    parser.add_argument("--euler-steps", type=int, default=100)
    parser.add_argument("--gif-fps", type=int, default=6)
    parser.add_argument("--gif-stride", type=int, default=1)
    parser.add_argument("--map-stride", type=int, default=10)
    static_group = parser.add_mutually_exclusive_group()
    static_group.add_argument("--use-static-features", dest="use_static_features", action="store_true")
    static_group.add_argument("--no-static-features", dest="use_static_features", action="store_false")
    parser.set_defaults(use_static_features=None)
    return parser.parse_args()


def main(opt: argparse.Namespace) -> None:
    set_seed(opt.seed)
    device = resolve_device(opt.device)
    da_seed = opt.seed if opt.da_seed is None else opt.da_seed

    cpu_rng = torch.Generator(device="cpu")
    cpu_rng.manual_seed(da_seed)
    device_rng = torch.Generator(device=device.type)
    device_rng.manual_seed(da_seed)

    base_path = opt.base_path
    data_root = _resolve_path(base_path, opt.data_root)
    dataset_path = _resolve_path(base_path, opt.dataset_path)
    model_path = _resolve_path(base_path, opt.model_path)
    encoder_path = _resolve_path(base_path, opt.encoder_checkpoint)
    output_dir = _resolve_path(base_path, opt.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    use_static_features = _infer_use_static_features(model_path, opt.use_static_features)

    dataset = torch.load(dataset_path, map_location="cpu", weights_only=False)
    obs_idx = dataset["meta"]["selected_obs_idx"]
    if isinstance(obs_idx, torch.Tensor):
        obs_idx = obs_idx.cpu().numpy()
    else:
        obs_idx = np.asarray(obs_idx)

    available_traj_ids = _list_trajectory_ids(data_root)
    background_traj_id = _select_background_traj_id(
        available_traj_ids,
        target_traj_id=opt.traj_id,
        requested_traj_id=opt.background_traj_id,
    )

    flow, coords, rain = _load_reduced_trajectory(data_root, opt.traj_id, use_static_features)
    _, _, rain_bg = _load_reduced_trajectory(data_root, background_traj_id, use_static_features)
    t_len = int(flow.shape[1])
    dim_u = int(rain.shape[-1])
    dim_y = int(flow.shape[-1])
    dim_x = int(coords.shape[-1])

    model = _load_ldnet_model(
        opt=opt,
        device=device,
        dim_u=dim_u,
        dim_x=dim_x,
        dim_y=dim_y,
    )
    encoder, enc_stats, encoder_normalized = _load_encoder(encoder_path, device)

    obs_truth = np.asarray(flow[0][:, obs_idx, :], dtype=np.float32)
    obs_noise = opt.obs_noise_std * torch.randn(obs_truth.shape, generator=cpu_rng, dtype=torch.float32)
    obs_noisy = obs_truth + obs_noise.numpy().astype(np.float32)

    obs_tensor = torch.from_numpy(obs_noisy.reshape(1, t_len, -1)).to(device)
    obs_mean = enc_stats["obs_mean"].to(device) if enc_stats["obs_mean"] is not None else None
    obs_std = enc_stats["obs_std"].to(device) if enc_stats["obs_std"] is not None else None
    latent_mean = enc_stats["latent_mean"].to(device) if enc_stats["latent_mean"] is not None else None
    latent_std = enc_stats["latent_std"].to(device) if enc_stats["latent_std"] is not None else None

    obs_tensor = _normalize(obs_tensor, obs_mean, obs_std)
    with torch.no_grad():
        obs_latent = encoder(obs_tensor).squeeze(0)
    obs_latent = _denormalize(obs_latent, latent_mean, latent_std)

    rain_tensor = torch.from_numpy(np.asarray(rain_bg, dtype=np.float32)).to(device)
    dummy_x = torch.zeros((1, t_len, 1, dim_x), dtype=torch.float32, device=device)
    x_map = np.load(data_root / f"coords_traj{opt.traj_id}.npy", mmap_mode="r")
    if use_static_features:
        static = np.load(data_root / f"static_features_traj{opt.traj_id}.npy", mmap_mode="r")
        x_map = np.concatenate([x_map, static], axis=-1)
    x_map = np.asarray(x_map, dtype=np.float32)

    mask_path = data_root / "aggregate_mask.npy"
    if not mask_path.exists():
        raise FileNotFoundError(f"Missing aggregate mask: {mask_path}")
    domain_mask = np.load(mask_path)
    if domain_mask.ndim != 2:
        raise ValueError(f"Expected aggregate mask with shape (H, W); got {domain_mask.shape}")
    h_dim, w_dim = domain_mask.shape
    scatter_indices = _resolve_scatter_indices(domain_mask, h_dim, w_dim, x_map)
    grid_to_reduced = -np.ones(h_dim * w_dim, dtype=np.int64)
    grid_to_reduced[scatter_indices] = np.arange(scatter_indices.size)

    map_stride = max(1, int(opt.map_stride))
    row_sel = np.arange(0, h_dim, map_stride, dtype=np.int64)
    col_sel = np.arange(0, w_dim, map_stride, dtype=np.int64)
    coarse_mask = domain_mask[np.ix_(row_sel, col_sel)].reshape(-1).astype(bool)
    coarse_flat = (row_sel[:, None] * w_dim + col_sel[None, :]).reshape(-1)
    coarse_reduced = grid_to_reduced[coarse_flat]
    coarse_reduced = coarse_reduced[coarse_mask]
    if coarse_reduced.size == 0:
        raise ValueError(f"Map stride {map_stride} produced no valid coarse cells.")
    coarse_shape = (row_sel.size, col_sel.size)
    coarse_valid_flat = np.flatnonzero(coarse_mask)
    coarse_coords = x_map[0, coarse_reduced, :].astype(np.float32, copy=False)
    x_map_coarse = np.broadcast_to(
        coarse_coords[None, None, :, :],
        (1, t_len, coarse_coords.shape[0], coarse_coords.shape[1]),
    ).copy()
    x_map_tensor = torch.from_numpy(x_map_coarse).to(device)

    x_vals = 2.0 * (col_sel.astype(np.float32) / float(w_dim) - 0.5)
    aspect = float(h_dim) / float(w_dim)
    y_vals = 2.0 * (row_sel.astype(np.float32) / float(h_dim) - 0.5) * aspect
    dx = float(np.diff(x_vals).mean()) if x_vals.size > 1 else 1.0
    dy = float(np.diff(y_vals).mean()) if y_vals.size > 1 else 1.0
    map_extent = (
        float(x_vals.min() - 0.5 * dx),
        float(x_vals.max() + 0.5 * dx),
        float(y_vals.min() - 0.5 * dy),
        float(y_vals.max() + 0.5 * dy),
    )

    with torch.no_grad():
        forecast_latent = model({"u": rain_tensor, "x": dummy_x, "dt": torch.tensor([1.0], device=device)}, device, latent_state=True)
        forecast_phys = model({"u": rain_tensor, "x": x_map_tensor, "dt": torch.tensor([1.0], device=device)}, device)

    forecast_latent = forecast_latent.squeeze(0)
    forecast_phys = forecast_phys.detach().cpu().numpy()

    state = torch.zeros(opt.ensemble_size, opt.num_latent_states, device=device)
    assim_latent_hist: list[torch.Tensor] = []
    forecast_prior_hist: list[torch.Tensor] = []

    for t in tqdm(range(t_len), desc="LD-ENSF", leave=False):
        u_t = rain_tensor[:, t, :].expand(opt.ensemble_size, -1)
        with torch.no_grad():
            state = state + model.dyn(torch.cat([u_t, state], dim=1))
        forecast_prior_hist.append(state.mean(dim=0).detach().cpu())

        state = _ensemble_score_posterior(
            prior=state,
            obs_latent=obs_latent[t],
            time_steps=opt.euler_steps,
            obs_sigma=opt.obs_sigma,
            latent_scaling=opt.latent_scaling,
            eps_alpha=opt.eps_alpha,
            generator=device_rng,
        )
        assim_latent_hist.append(state.mean(dim=0).detach().cpu())

    assim_latent = torch.stack(assim_latent_hist, dim=0).numpy()
    forecast_prior_latent = torch.stack(forecast_prior_hist, dim=0).numpy()

    truth_phys = np.asarray(flow[0][:, coarse_reduced, :], dtype=np.float32)
    truth_grid = _series_to_grid(truth_phys[:, :, 0], coarse_shape, coarse_valid_flat)
    forecast_grid = _series_to_grid(forecast_phys[0, :, :, 0], coarse_shape, coarse_valid_flat)

    assim_phys = np.empty_like(forecast_phys, dtype=np.float32)
    x_map_single = x_map_tensor[:, 0, :, :]
    with torch.no_grad():
        for t in range(t_len):
            latent_t = torch.from_numpy(assim_latent[t : t + 1]).to(device)
            pred_t = model._decode_points(x_map_single, latent_t, chunk_size=model.chunk_size)
            assim_phys[0, t] = pred_t[0].detach().cpu().numpy()
    assim_grid = _series_to_grid(assim_phys[0, :, :, 0], coarse_shape, coarse_valid_flat)

    obs_values = obs_noisy[:, :, 0].astype(np.float32, copy=False)
    obs_truth_values = obs_truth[:, :, 0].astype(np.float32, copy=False)
    obs_err_values = np.abs(obs_values - obs_truth_values).astype(np.float32, copy=False)
    obs_coords = x_map[0, obs_idx, :2].astype(np.float32, copy=False)

    sample_idx = np.linspace(0, t_len - 1, min(t_len, 12), dtype=int)
    truth_sample = truth_grid[sample_idx].ravel()
    forecast_sample = forecast_grid[sample_idx].ravel()
    assim_sample = assim_grid[sample_idx].ravel()
    left_samples = np.concatenate([truth_sample, forecast_sample, assim_sample])
    left_samples = left_samples[np.isfinite(left_samples)]
    if left_samples.size == 0:
        left_vmin, left_vmax = 0.0, 1.0
    else:
        left_vmin = min(0.0, float(np.nanpercentile(left_samples, 0.5)))
        left_vmax = float(np.nanpercentile(left_samples, 99.5))
        if not np.isfinite(left_vmax) or left_vmax <= left_vmin:
            left_vmin, left_vmax = 0.0, max(1.0, float(np.nanmax(left_samples)))

    err_samples = np.concatenate(
        [
            np.abs(forecast_grid[sample_idx] - truth_grid[sample_idx]).ravel(),
            np.abs(assim_grid[sample_idx] - truth_grid[sample_idx]).ravel(),
            obs_err_values[sample_idx].ravel(),
        ]
    )
    err_samples = err_samples[np.isfinite(err_samples)]
    if err_samples.size == 0:
        err_vmax = 1.0
    else:
        err_vmax = float(np.nanpercentile(err_samples, 99.5))
        if not np.isfinite(err_vmax) or err_vmax <= 0:
            err_vmax = max(1.0, float(np.nanmax(err_samples)))

    final_forecast_err = _relative_l2_scalar(truth_grid[-1], forecast_grid[-1])
    final_assim_err = _relative_l2_scalar(truth_grid[-1], assim_grid[-1])
    final_forecast_r2 = _r2_scalar(truth_grid[-1], forecast_grid[-1])
    final_assim_r2 = _r2_scalar(truth_grid[-1], assim_grid[-1])
    traj_forecast_rel_rmse, traj_forecast_rmse, traj_forecast_r2 = _trajectory_metrics(truth_grid, forecast_grid)
    traj_assim_rel_rmse, traj_assim_rmse, traj_assim_r2 = _trajectory_metrics(truth_grid, assim_grid)

    print(f"Trajectory id: {opt.traj_id}")
    print(f"Forecast rain trajectory id: {background_traj_id}")
    print(f"Observation points: {len(obs_idx)}")
    print(f"Using static features: {use_static_features}")
    print(f"DA seed: {da_seed}")
    print(f"Final relative L2 error - forecast: {final_forecast_err:.4f}")
    print(f"Final relative L2 error - assimilation: {final_assim_err:.4f}")
    print(f"Final R^2 - forecast: {final_forecast_r2:.4f}")
    print(f"Final R^2 - assimilation: {final_assim_r2:.4f}")
    print(f"Trajectory relative RMSE - forecast: {traj_forecast_rel_rmse:.4f}")
    print(f"Trajectory relative RMSE - assimilation: {traj_assim_rel_rmse:.4f}")
    print(f"Trajectory R^2 - forecast: {traj_forecast_r2:.4f}")
    print(f"Trajectory R^2 - assimilation: {traj_assim_r2:.4f}")
    print(f"Encoder normalized input: {encoder_normalized}")

    npz_path = output_dir / f"traj_{opt.traj_id}_ldensf_results.npz"
    np.savez_compressed(
        npz_path,
        truth_grid=truth_grid,
        forecast_grid=forecast_grid,
        assim_grid=assim_grid,
        obs_coords=obs_coords,
        obs_values=obs_values,
        obs_truth_values=obs_truth_values,
        obs_err_values=obs_err_values,
        forecast_latent=forecast_latent.detach().cpu().numpy(),
        forecast_prior_latent=forecast_prior_latent,
        assim_latent=assim_latent,
        forecast_rain_traj_id=int(background_traj_id),
        final_forecast_err=final_forecast_err,
        final_assim_err=final_assim_err,
        final_forecast_r2=final_forecast_r2,
        final_assim_r2=final_assim_r2,
        traj_forecast_rel_rmse=traj_forecast_rel_rmse,
        traj_assim_rel_rmse=traj_assim_rel_rmse,
        traj_forecast_rmse=traj_forecast_rmse,
        traj_assim_rmse=traj_assim_rmse,
        traj_forecast_r2=traj_forecast_r2,
        traj_assim_r2=traj_assim_r2,
        obs_idx=obs_idx,
    )

    gif_path = output_dir / f"traj_{opt.traj_id}_ldensf.gif"
    _make_map_gif(
        time=np.arange(t_len),
        truth_grid=truth_grid,
        obs_coords=obs_coords,
        obs_values=obs_values,
        obs_err_values=obs_err_values,
        forecast_grid=forecast_grid,
        assim_grid=assim_grid,
        left_vmin=left_vmin,
        left_vmax=left_vmax,
        err_vmax=err_vmax,
        extent=map_extent,
        out_path=gif_path,
        fps=opt.gif_fps,
        stride=opt.gif_stride,
    )

    print(f"Saved results to: {npz_path}")
    print(f"Saved GIF to: {gif_path}")


if __name__ == "__main__":
    main(create_options())
